ANDROID: fix incorrect merge conflict resolution in i3c
Kernelci flagged a warning during an allmodconfig build:

drivers/i3c/master/svc-i3c-master.c:1100:29: error: variable 'reg' is uninitialized when used here
drivers/i3c/master/svc-i3c-master.c:1040:9: note: initialize the variable 'reg' to silence this warning

Kernelci link: https://linux.kernelci.org/build/android/branch/android15-6.6/kernel/ASB-2024-11-05_15-6.6-58-g5fb2cda477084/

It turns out that a merge resolution left out the code that initializes reg, so this
patch puts it back.

	ret = readl_poll_timeout(master->regs + SVC_I3C_MSTATUS, reg,
			SVC_I3C_MSTATUS_MCTRLDONE(reg), 0, 1000);
	if (ret)
		goto emit_stop;

Fixes: 18bea82acf6f ("Merge 6.6.51 into android15-6.6-lts")
Signed-off-by: Todd Kjos <tkjos@google.com>
Change-Id: I91471af7fe69c17d33fbfe4f51016f51a6752b4b