Fix compile errors
8475/8450/7450/6450/7435 U: Upmerge
to r2.0.1.r1_00012.0, have the compile error:
msm-kernel/drivers/scsi/ufs/vendor/ufsfeature.h:53:2:
error: redefinition of enumerator 'UFSHCD_EH_IN_PROGRESS'

Need to remove the redefinition UFSHCD_EH_IN_PROGRESS

Change-Id: I2864b1191af4f9edb622ecae32db7b3e246523e2
Signed-off-by: Zhiye Li <lizy90@motorola.com>
Reviewed-on: https://gerrit.mot.com/2922235
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Tested-by: Jira Key
Reviewed-by: Dongliang Yue <yuedl1@motorola.com>
Reviewed-by: Zonghua Liu <a17671@motorola.com>
Reviewed-by: Chuanchun Zhu <zhucc2@motorola.com>
Reviewed-by: Zhenxin Xi <xizx@motorola.com>
Submit-Approved: Liyun Zhang <zhangl19@motorola.com>
Reviewed-on: https://gerrit.mot.com/3101772
Reviewed-by: Carlos Pinho <cpinho@motorola.com>
Submit-Approved: Carlos Pinho <cpinho@motorola.com>