ANDROID: vendor_hooks: add missing forward declare for struct cma
A recent vendor hook addition is missing a declaration for struct cma:

In file included from init/main.c:61:
In file included from ./include/linux/rmap.h:16:
In file included from ./include/trace/hooks/mm.h:6:
./include/trace/hooks/mm.h:253:18: error: declaration of 'struct cma' will not be visible outside of this function [-Werror,-Wvisibility]
        TP_PROTO(struct cma *cma, unsigned long count, unsigned int align,

Bug: 299425220
Fixes: d1051298accf ("ANDROID: vendor_hooks: add vendor hook in cma_alloc()")
Change-Id: I5565ec92a468896600abb78bce077d0dd10c68b3
Signed-off-by: T.J. Mercier <tjmercier@google.com>