abi: Fix wlan module build error in GKI build
qca_cld3_xxx.ko compile failure when make user build add whitelist

ERROR: "init_task" [../../vendor/qcom/opensource/wlan/qcacld-3.0/.qca6390/wlan.ko] undefined!
ERROR: "sock_from_file" [../../vendor/qcom/opensource/wlan/qcacld-3.0/.qca6390/wlan.ko] undefined!

Change-Id: Icb2c09bf24325d243939bec6c69a9ca36abce4c8
Signed-off-by: sunyue5 <sunyue5@motorola.com>
Reviewed-on: https://gerrit.mot.com/2244333
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Tested-by: Jira Key
Reviewed-by: Xiangpo Zhao <zhaoxp3@motorola.com>
Submit-Approved: Jira Key
(cherry picked from commit c284adb02295bb3957431144862ae19c96420a1e)
Reviewed-on: https://gerrit.mot.com/2244347
Reviewed-by: Huosheng Liao <liaohs@motorola.com>