ANDROID: Fix 32-bit kernelci build break
The fix for the ABI build-break was broken for 32-bit builds because the
struct sizes changed which tripped a static assertion checking size and
alignment of the KMI stable type. Since the KMI is not stable for
32-bit, resolve by suppressing this check for 32-bit builds.

./include/linux/android_kabi.h:43:17: error: static assertion failed: "include/linux/cgroup-defs.h:588: struct callback_head rcu is larger than u8 __attribute__((__aligned__(8))) android_backport_reserved1[CGROUP_SUBSYS_COUNT * sizeof(atomic_t)]"
   43 |                 _Static_assert(sizeof(struct{_new;}) <= sizeof(struct{_orig;}), \
      |                 ^~~~~~~~~~~~~~
./include/linux/android_kabi.h:67:17: note: in expansion of macro ‘__ANDROID_KABI_CHECK_SIZE_ALIGN’
   67 |                 __ANDROID_KABI_CHECK_SIZE_ALIGN(_orig, _new);   \
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/android_kabi.h:157:9: note: in expansion of macro ‘_ANDROID_KABI_REPLACE’
  157 |         _ANDROID_KABI_REPLACE(_ANDROID_BACKPORT_RESERVE_ARRAY(number, bytes), _new)
      |         ^~~~~~~~~~~~~~~~~~~~~
./include/linux/cgroup-defs.h:588:9: note: in expansion of macro ‘ANDROID_BACKPORT_USE_ARRAY’
  588 |         ANDROID_BACKPORT_USE_ARRAY(1, CGROUP_SUBSYS_COUNT * sizeof(atomic_t),
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~

Bug: 381949343
Fixes: d66e9166bfa1 ("ANDROID: fix ABI-break in struct cgroup_root")
Signed-off-by: Todd Kjos <tkjos@google.com>
Change-Id: Ied0ca3e4d892014582c921d311fdab652a76adf6
(cherry picked from commit fa2752f439942a680289ebfcc83a4ae05282e5a7)