ANDROID: fix kernelci issue in fs/fuse/dir.c
Fields were added to struct fuse_args which caused the stack to
increase beyone the expected 1024 bytes for arm32 builds. This
manifested as an error during allmodconfig builds in kernelci:

fs/fuse/dir.c:2142:5: error: stack frame size (1032) exceeds limit (1024) in 'fuse_do_setattr'

Workaround the issue by increasing the expected stack frame size for
dir.o.

Fixes: 8b16bb6b6f0a ("ANDROID: fuse-bpf: fuse-bpf v1.2")
Signed-off-by: Todd Kjos <tkjos@google.com>
Change-Id: I95134ea360e8f9be4bd283db38242f107b4cf7eb